//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class movie
    {
        public int idMovie { get; set; }
        public string year { get; set; }
        public string description { get; set; }
        public string movieType { get; set; }
        public string genre { get; set; }
        public string title { get; set; }
        public string watched { get; set; }
    }
}
